name: Build
description: Build Redis image
inputs:
  version:
    description: redis version
    required: true
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
    - name: Build image
      env:
        REDIS_VERSION: ${{ inputs.version }}
        TARGET_PLATFORM: ${{ inputs.platform }}
        TAGS: ${{ inputs.tags }}
      run: |
        set -e
        make buildx-build-amd64
        make buildx-build
        . $GITHUB_ACTION_PATH/release.sh
      shell: bash