name: Build Docker Image

on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        name: Generate Strategy
        run: echo "matrix=$(jq -c . < ./versions.json)" >> $GITHUB_OUTPUT
  build:
    needs: generate-strategy
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-strategy.outputs.matrix) }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo ${{ matrix.name }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.directory }}/"
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ matrix.tags }}