name: Build Docker Image

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-redis72:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ['7.2', '7.2.4', 'latest']
        platform: ['linux/amd64', 'linux/arm64']
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PA_TOKEN }}
      - name: 'Build & Push PHP Image'
        run: make release REDIS_VERSION=7.2 TAG=${{ matrix.tags }} PLATFORM=${{ matrix.platform }}